### ISSUE TITLE
Setup fails because README.txt is not found

### ISSUE THREAD

**Issue by efflicto** [scaramallion/pynetdicom#38]
> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    long_description = open('README.txt').read(),
IOError: [Errno 2] No such file or directory: 'README.txt'

**Comment by scaramallion** [comment]
Should be OK now

**Comment by efflicto** [comment]
It's working. Thank you! (also for working on this project!)

**Comment by scaramallion** [comment]
No problem, thanks for letting me know.
