### ISSUE TITLE
MemoryError after getting ~520 images

### ISSUE THREAD

**Issue by efflicto** [scaramallion/pynetdicom#41]
Hi,

this is my testing code: http://pastebin.com/HZ5C23Sz

The transfer starts to slow down and after around 520 images the following exception occurs:
> Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pynetdicom\association.py", line 323, in run
    msg, msg_context_id = self.dimse.Receive(False, self.dimse_timeout)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pynetdicom\DIMSEprovider.py", line 264, in Receive
    if self.message.Decode(primitive):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pynetdicom\DIMSEmessages.py", line 267, in Decode
    self.data_set.write(pdv_item[1][1:])
MemoryError

I used pympler to track the memory usage:
At start:

>                                types |   # objects |   total size
==================================== | =========== | ============
                         <class 'str |       19685 |      2.87 MB
                        <class 'dict |        2976 |      1.11 MB
                        <class 'code |        6768 |    529.11 KB
                        <class 'type |        1003 |    505.08 KB
                       <class 'tuple |        2772 |    101.99 KB
                         <class 'set |         425 |     94.64 KB
                     <class 'weakref |        1689 |     72.57 KB
          <class 'wrapper_descriptor |        1623 |     69.74 KB
                        <class 'list |         838 |     65.41 KB
           <class 'method_descriptor |        1228 |     47.97 KB
           <class 'getset_descriptor |        1138 |     44.45 KB
  <class 'builtin_function_or_method |        1100 |     42.97 KB
                 function (__init__) |         585 |     41.13 KB
                         <class 'int |        2370 |     36.88 KB
                 <class 'abc.ABCMeta |          55 |     26.23 KB

When the error occurs:

>                                     types |   # objects |   total size
========================================= | =========== | ============
                             <class 'list |      148021 |     36.35 MB
                            <class 'bytes |        5772 |     16.24 MB
                              <class 'str |      170638 |      9.81 MB
                             <class 'dict |        3832 |      1.27 MB
                             <class 'code |        6787 |    530.59 KB
                             <class 'type |        1003 |    509.72 KB
              <class 'pydicom.tag.BaseTag |       10684 |    332.38 KB
  <class 'pydicom.dataelem.RawDataElement |        5773 |    315.71 KB
                              <class 'int |       18364 |    268.35 KB
                            <class 'tuple |        2843 |    104.59 KB
                              <class 'set |         425 |     94.64 KB
                      <class '_io.BytesIO |           2 |     81.91 KB
                          <class 'weakref |        1694 |     72.79 KB
               <class 'wrapper_descriptor |        1624 |     69.78 KB
                  <class 'pydicom.uid.UID |         616 |     49.15 KB

So no memory usage is not too big but the count of the objects gets very high. 
147183 list objects got created in the progress.
Here are my testing images: https://dl.0x05.de/E0014589.zip

Thank you in advance

**Comment by scaramallion** [comment]
Hmm, interesting. I've never tested large workloads. Do things improve if you restrict your C-STORE operations to say 300 datasets per association (if possible)?

The multi-threading definitely needs an overhaul, but I don't have much experience with it so I've been putting it off. Looks like I'll have to dig into it after all.

**Comment by efflicto** [comment]
I can't determine how many images I get. I have no control over the sender. I'll get much larger studies such like PET-CTs with ~3000 images per study.
The slowness begins after the first 10 images and gets worse until the memory error occurs. So even at around 200 images/association it's very very slow. 

Maybe I can dig in a bit and look for some leaks.

**Comment by scaramallion** [comment]
Sure, that'd be great. Like I said before I'm a bit busy at the moment. The likeliest culprit is probably something in the main loops in Association.run() and DULServiceProvider.run(). I've had a quick look but nothing jumps out at me.

**Comment by efflicto** [comment]
No hurry. Maybe I can dig in. I'm not the best python debugging expert. :)
Thanks!

**Comment by efflicto** [comment]
It seems that it isn't the lists objects what causes the error. It has to do with the data_set in DIMSEmessages.py.

**Comment by scaramallion** [comment]
It may be that data_set attribute isn't being reset when a complete DIMSE message is received. If that's the cause then it's an easy fix.

**Comment by efflicto** [comment]
The BytesIO buffered stream is growing with every image until it crashes. 

> types |   # objects |   total size
> <class '_io.BytesIO | 2 |    263.32 MB

So how you suggested there must be a missing destructor for this instance. But I'm not deep enough into the code to resolve it.

**Comment by scaramallion** [comment]
The latest commit fixes the immediate problem but it looks like there are still memory leaks as the C-STORE operations get slower and slower.

**Comment by scaramallion** [comment]
Whoops nope that just breaks everything. `dimse_msg` isn't a new object...

**Comment by scaramallion** [comment]
Ok, second time's the charm. Try this commit: fa026b4c6b113d4cfae906b1d3262287d3590155

**Comment by scaramallion** [comment]
It looks like that last commit fixes the slowdown too, I've tested up to 5000 datasets per assoc and the time per 100 transfers remained constant.

**Comment by efflicto** [comment]
Tested it. Works very good. Thank you!
